FROM python:3.9-slim
WORKDIR /app
COPY visualizar_datos.py /app/visualizar_datos.py
RUN pip install pandas geopandas matplotlib requests shapely fiona pyproj rtree
CMD ["python", "/app/visualizar_datos.py"]
